name: 🔧 Technical Debt / Refactor
description: Code quality improvements, refactoring, or architectural changes
title: "[Tech Debt]: "
labels: ["tech-debt", "refactor"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for internal improvements that don't directly add features but improve code quality, maintainability, or performance.

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What's the current implementation and why is it problematic?
      placeholder: |
        The current implementation does X which causes:
        - Problem 1
        - Problem 2
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Change
      description: What should we change and why is it better?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Analysis
      description: What files/components are affected? What could break?
      placeholder: |
        Files affected:
        - file1.py
        - file2.py
        
        Risk areas:
        - ...
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type of Change
      options:
        - Refactor - Same behavior, cleaner code
        - Performance - Speed or resource optimization
        - Architecture - Structural changes
        - Dependencies - Update/replace dependencies
        - Testing - Add/improve tests
        - Documentation - Code docs, comments, README
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical - Blocking development
        - High - Causing frequent issues
        - Medium - Improving maintainability
        - Low - Nice to have cleanup
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      options:
        - Small (< 1 day)
        - Medium (1-3 days)
        - Large (1-2 weeks)
        - XL (> 2 weeks)
    validations:
      required: true

  - type: textarea
    id: migration
    attributes:
      label: Migration Plan
      description: If this is a breaking change, how do we migrate?
      placeholder: |
        1. Step 1
        2. Step 2
        3. Verification

  - type: textarea
    id: tests
    attributes:
      label: Testing Strategy
      description: How do we verify this doesn't break anything?
